#ifndef TARGET_GLOBAL_H
#define TARGET_GLOBAL_H
#include <QDateTime>
#include <QString>
#include <QListView>
#include <QTreeView>
#include <QTreeWidgetItem>
#include <QPushButton>
#include <QLabel>
#include <QTabBar>
#include <QListWidget>
#include <QTcpServer>
#include <QTcpSocket>
#include <QSerialPort>
#include <QSerialPortInfo>
#include <QtSql>
#include <QTreeWidget>
#include <QCryptographicHash>
#include <QComboBox>
#include <QFile>
#include <QFrame>
#include <QGraphicsView>
#include <QtWidgets>
#include <QTime>
#include <QDate>
#include <QColor>
#include <QGraphicsItem>
#include <QtCore/qmath.h>
#include <QList>
#include <QMap>
#include <QVariant>
#include <QStringList>
#include <QThread>
#include <QSettings>
#include <QWidget>
#include <QSqlTableModel>
#include <QPaintDevice>
#include <QPropertyAnimation>
#endif